name: NASA Project Cl
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs: 
  build:
    needs: 
      runs-on: ubuntu-latest
      steps:
        -uses: actions/checkout@v2
        -name: use Nodejs version 16
        -uses: actions/setup-node@v2
        with:
          nodeversion: '16'
        -run: npm install
        -run: npm run build ---prefix client
